### ISSUE TITLE
Error show.blade.php

### ISSUE THREAD

**Issue by ghost** [laraviet/BookCRUD#1]
Method Illuminate\Database\Query\Builder::getTitle does not exist. (View: /home/vagrant/code/LaraProject/vendor/laraviet/book-crud/src/resources/views/books/show.blade.php)

**Comment by laraviet** [comment]
Thank for feedback. I already fix this issue. You can check now

**Comment by ghost** [comment]
Wow amazing

**Comment by ghost** [comment]
I must say thank you to yours Laravel series. I learn from them a lot.

**Comment by laraviet** [comment]
Thank you :)
